<?php

use Illuminate\Support\Facades\Route;

// Serve the service worker from root scope so it can control all pages.
// The actual file lives at public/build/sw.js (generated by vite-plugin-pwa).
Route::get('/sw.js', function () {
    $swPath = public_path('build/sw.js');
    if (! file_exists($swPath)) {
        abort(404);
    }

    return response()->file($swPath, [
        'Content-Type' => 'application/javascript',
        'Service-Worker-Allowed' => '/',
    ]);
});

Route::get('/{any}', function () {
    return view('app');
})->where('any', '.*');
